"""RoboSpec Training Script — RoboSpec-Velocity-Flat-Anymal-D-v0

Generated by RoboSpec. Run with:
    cd <your-IsaacLab-directory>
    ./isaaclab.sh -p <path-to>/train.py --headless [--num_envs 64] [--video]

This script registers the environment, then delegates to Isaac Lab's
built-in training infrastructure. The real training script handles
AppLauncher, simulation init, and the RL training loop.
"""

import os
import sys

# ── Add config directory to sys.path so env_cfg module is importable ────
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _SCRIPT_DIR)

# ── Register environment (string-based — no isaaclab imports needed) ────
# gymnasium.register() stores entry points as strings and resolves them
# lazily, so this is safe to call before Isaac Sim / AppLauncher boots.
import gymnasium as gym

gym.register(
    id="RoboSpec-Velocity-Flat-Anymal-D-v0",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    disable_env_checker=True,
    kwargs={
        "env_cfg_entry_point": "anymal_d_flat_env_cfg:AnymalDFlatEnvCfg",
        "rsl_rl_cfg_entry_point": "isaaclab_tasks.manager_based.locomotion.velocity.config.anymal_d.agents.rsl_rl_ppo_cfg:AnymalDFlatPPORunnerCfg",
        "skrl_cfg_entry_point": "isaaclab_tasks.manager_based.locomotion.velocity.config.anymal_d.agents:skrl_flat_ppo_cfg.yaml",
    },
)

# ── Find Isaac Lab installation ─────────────────────────────────────────
_ISAACLAB_DIR = None
for candidate in [
    os.environ.get("ISAACLAB_DIR"),
    os.path.expanduser("~/IsaacLab"),
    "/home/ubuntu/IsaacLab",
    "/root/IsaacLab",
]:
    if candidate and os.path.isdir(str(candidate)):
        _ISAACLAB_DIR = candidate
        break

if _ISAACLAB_DIR is None:
    print("ERROR: Cannot find IsaacLab directory.")
    print("Set ISAACLAB_DIR env var or clone IsaacLab to ~/IsaacLab")
    sys.exit(1)

# ── Locate the framework training script ────────────────────────────────
_TRAIN_SCRIPT = os.path.join(
    _ISAACLAB_DIR,
    "scripts", "reinforcement_learning",
    "rsl_rl", "train.py"
)

if not os.path.exists(_TRAIN_SCRIPT):
    print(f"ERROR: Training script not found: {_TRAIN_SCRIPT}")
    print("Install the framework: ./isaaclab.sh --install rsl_rl")
    sys.exit(1)

# ── Inject default args and delegate to the real training script ────────
# The real train.py handles AppLauncher, argparse, and the full training
# loop. We just need to ensure --task and --num_envs are set.
_user_args = sys.argv[1:]  # preserve user-supplied flags (--headless etc.)

# Inject defaults only if the user didn't provide them
if "--task" not in _user_args:
    _user_args = ["--task", "RoboSpec-Velocity-Flat-Anymal-D-v0"] + _user_args
if "--num_envs" not in _user_args:
    _user_args = ["--num_envs", "1024"] + _user_args

sys.argv = [_TRAIN_SCRIPT] + _user_args

print(f"{'='*70}")
print(f"  RoboSpec Training: RoboSpec-Velocity-Flat-Anymal-D-v0")
print(f"  Framework: rsl_rl")
print(f"  Args: {' '.join(_user_args)}")
print(f"{'='*70}")

import runpy
runpy.run_path(_TRAIN_SCRIPT, run_name="__main__")
